### ISSUE TITLE
Northern Ireland postcodes are appended without preprocessing

### ISSUE THREAD

**Issue by iAlex97** [osm-search/gb-postcode-data#12]
Currently as it is stated in the readme, NI postcodes are simply append to the list of "processed" GB postcodes by doing:
```
grep -v postcode NI-postcodes.csv >> gb_and_ni_postcodes.csv
```

```
head NI-postcodes.csv
postcode,lat,lon
BTB5 6SW,54.29280309000000,-6.37513798000000
BTB5 6SW,54.29280308999999,-6.37513798000000
BT94 5NG,54.2748323,-7.570184
BT94 5NF,54.28304900000000,-7.55462400000000
```

shows NI that postcodes have between 6 and 16 decimal digits. The python which processes the GB postcodes truncates them to 5 digits as required by WGS84, so I'm wondering if the grep line should be changed to:
```
awk 'BEGIN {FS=OFS=","} NR>1 {printf "%s,%.5f,%.5f\n", $1, $2, $3}' NI-postcodes.csv >> gb_and_ni_postcodes.csv
```

**Comment by iAlex97** [comment]
Comparing the 2 "datasets" shows subtle changes:
```bash
cp gb_postcodes.csv gb_and_ni_postcodes.old.csv
cp gb_postcodes.csv gb_and_ni_postcodes.new.csv

grep -v postcode NI-postcodes.csv >> gb_and_ni_postcodes.old.csv
awk 'BEGIN {FS=OFS=","} NR>1 {printf "%s,%.5f,%.5f\n", $1, $2, $3}' NI-postcodes.csv >> gb_and_ni_postcodes.new.csv

./compare.py gb_and_ni_postcodes.csv gb_and_ni_postcodes.new.csv
Read 1743529 postcodes from old file gb_and_ni_postcodes.csv
Read 1743529 postcodes from new file gb_and_ni_postcodes.new.csv
Added: 0 (0.000%)
Deleted: 0 (0.000%)
Position moved: 9693 (0.556%)
Position moved more than 100 meters: 0 (0.000%)
Position moved more than 1000 meters: 0 (0.000%)
Position moved more than 10000 meters: 0 (0.000%)
Average distance difference of all updates: 0.35 meters
```

**Comment by mtmail** [comment]
Good idea. The number of duplicates surprises me as well and will need a bit more logic to remove. https://csvkit.readthedocs.io/en/latest/scripts/csvjoin.html

**Comment by mtmail** [comment]
The GB dataset is from an official source, the national mapping agency (who get their data from the Royalmail postal agency). The NI dataset is crawled (https://github.com/osm-uk/NI-Postcodes). I'd give the official source preference.

**Comment by iAlex97** [comment]
I agree that official sources should take priority over crawled data, but I see no overlapping postcodes joining the GB and NI csv files:

```bash
csvjoin -c postcode NI-postcodes.csv gb_postcodes.csv
postcode,lat,lon,lat2,lon2
```

However, the NI csv indeed contains multiple pairs of coordinates for one postcode and I was wondering what is the best way to prepare them for Nominatim import. I am not very familiar with the intricacies of how Nominatim actually indexes the external postcodes, but judging from your response external datasources should only provide unique postcodes and their coordinates.

The following script aggregates the NI dataset by "reducing" identical postcodes by averaging their coordinates.

```python

#!/usr/bin/env python3
from csv import DictReader, DictWriter
from lib.convert import normalize_postcode, check_postcode


##
## CSV Output
##
fields = ['postcode', 'lat', 'lon']


accumulator = {}

with open("NI-postcodes.csv") as file:
    csv_reader = DictReader(file, fieldnames=fields)
    for row in csv_reader:
        postcode = normalize_postcode(row['postcode'])

        if not check_postcode(postcode):
            print("invalid postcode '%s'" % postcode)
            continue

        lat = float(row['lat'])
        lon = float(row['lon'])
        pc = accumulator.get(postcode)
        if pc is not None:
            accumulator[postcode] = ((pc[0] + lat) / 2, (pc[1] + lon) / 2)
        else:
            accumulator[postcode] = (lat, lon)



with open("NI-postcodes-agg.csv", 'wt') as out_file:
    csv_writer = DictWriter(out_file, fieldnames=fields, lineterminator="\n")
    csv_writer.writeheader()

    for postcode, location in accumulator.items():
        csv_writer.writerow({
            'postcode': postcode,
            'lat': '%0.5f' % location[0],
            'lon': '%0.5f' % location[1]
        })
```

It seems that after running this, it outputs a little under 10k postcodes:
```
wc -l NI-postcodes*
   9772 NI-postcodes-agg.csv
  27109 NI-postcodes.csv
  36881 total
```

Let me know if this approach looks okay to you.

**Comment by mtmail** [comment]
You're right, I counted duplicates but they're all within the NI- part of the database. Your script looks great. Can you create a PR?

**Comment by iAlex97** [comment]
Sure thing

**Comment by mtmail** [comment]
@iAlex97 Wonderful, thanks a lot! I updated the documentation.

**Comment by iAlex97** [comment]
Cool, thank you for the timely feedback!
